In [17]:
import numpy as np
import fractions
np.set_printoptions(formatter={'all':lambda x: str(fractions.Fraction(x).limit_denominator())})

In [10]:
X = np.array([6, 0, 0])
b1 = np.array([1, 1, 1])
b2 = np.array([0, 1, 2])
B = np.array([[1, 0],[1, 1], [1, 2]])
X, B, b1, b2

(array([6, 0, 0]),
 array([[1, 0],
        [1, 1],
        [1, 2]]),
 array([1, 1, 1]),
 array([0, 1, 2]))

In [12]:
pux = (B @ np.linalg.inv(B.T @ B) @ B.T @ X)
pux

array([ 5.,  2., -1.])

In [18]:
pmat = (B @ np.linalg.inv(B.T @ B) @ B.T)
pmat

array([[5/6, 1/3, -1/6],
       [1/3, 1/3, 1/3],
       [-1/6, 1/3, 5/6]])

In [20]:
np.linalg.matrix_rank(pmat)

2

In [21]:
X = np.array([3, 2, 2])
B = np.array([[1, 0],[0,1],[0,1]])
pux = (B @ np.linalg.inv(B.T @ B) @ B.T @ X)
pux

array([3, 2, 2])

In [28]:
X = np.array([12, 0, 0])
B = np.array([[1, 0],[1,1],[1,2]])
pux = (B @ np.linalg.inv(B.T @ B) @ B.T @ X)
pux

array([10, 4, -2])